/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class GuiElement extends javax.swing.JFrame {

    /**
     * Creates new form GuiElements
     */
    public GuiElement() {
        initComponents();
    }

    public javax.swing.JPanel getAccountInfo() {
        return this.accountInput;
    }

    public boolean isDateString(String str) {
        try {
            new SimpleDateFormat("dd/MM/yyyy").parse(str);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public boolean isDoubleString(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public boolean verifInput() {
        infoMsg.setText("");
        infoMsg.setForeground(Color.red);
        if (accNoInput.getText().trim().length() == 0) {
            infoMsg.setText("Complete all account info!");
            return false;
        } else if (!isDoubleString(accNoInput.getText().trim())) {
            infoMsg.setText("Account number invalid!");
            return false;
        } else if (sortcodeInput.getText().trim().length() == 0) {
            infoMsg.setText("Complete all account info!");
            return false;
        } else if (balanceInput.getText().trim().length() == 0) {
            infoMsg.setText("Complete all account info!");
            return false;
        } else if (!isDoubleString(balanceInput.getText().trim())) {
            infoMsg.setText("Balance amount invalid!");
            return false;
        } else if (nameOfBankInput.getText().trim().length() == 0) {
            infoMsg.setText("Complete all account info!");
            return false;
        } else if (rateInput.getText().trim().length() == 0) {
            infoMsg.setText("Complete all account info!");
            return false;
        } else if (!isDoubleString(rateInput.getText().trim())) {
            infoMsg.setText("Rate is invalid!");
            return false;
        } else if (lastRDateInput.getText().trim().length() == 0) {
            infoMsg.setText("Complete all account info!");
            return false;
        } else if (!isDateString(lastRDateInput.getText().trim())) {
            infoMsg.setText("Last Reported Date is invalid!");
            return false;
        } else {
            infoMsg.setForeground(Color.green);
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        displayAccInfo = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        accountInput = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sortcodeInput = new javax.swing.JTextField();
        accNoInput = new javax.swing.JTextField();
        balanceInput = new javax.swing.JTextField();
        nameOfBankInput = new javax.swing.JTextField();
        rateInput = new javax.swing.JTextField();
        lastRDateInput = new javax.swing.JTextField();
        jointInput = new javax.swing.JComboBox<>();
        createBtn = new javax.swing.JButton();
        infoMsg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        accountInfo = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        lastRDate = new javax.swing.JLabel();
        sortCode = new javax.swing.JLabel();
        accNo = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        nameOfBank = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        createdOnDate = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        transactionsNbr = new javax.swing.JLabel();
        noAccountErrMsg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        depositWithdrawPanel = new javax.swing.JPanel();
        withdrawBtn = new javax.swing.JButton();
        depositBtn = new javax.swing.JButton();
        TXNAmount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Account No");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Balance");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Name of Bank");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Rate");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Last Reported Date");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Joint");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("SortCode");

        jointInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        createBtn.setBackground(new java.awt.Color(0, 51, 51));
        createBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("create");

        infoMsg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoMsg.setForeground(new java.awt.Color(255, 0, 51));
        infoMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout accountInputLayout = new javax.swing.GroupLayout(accountInput);
        accountInput.setLayout(accountInputLayout);
        accountInputLayout.setHorizontalGroup(
            accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInputLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(accountInputLayout.createSequentialGroup()
                        .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(95, 95, 95)
                        .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountInputLayout.createSequentialGroup()
                                .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sortcodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(29, 29, 29)
                                .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastRDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jointInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(accountInputLayout.createSequentialGroup()
                                .addComponent(nameOfBankInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addComponent(createBtn)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        accountInputLayout.setVerticalGroup(
            accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInputLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountInputLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(accNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13))
                    .addComponent(sortcodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(accountInputLayout.createSequentialGroup()
                        .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(rateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lastRDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(balanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jointInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(accountInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nameOfBankInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createBtn))
                .addGap(18, 18, 18)
                .addComponent(infoMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(accountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(accountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        displayAccInfo.addTab("create accounts info", jPanel1);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Account No");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Balance");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Name of Bank");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Rate");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Last Reported Date");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("SortCode");

        rate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rate.setText(" ");

        lastRDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastRDate.setText(" ");

        sortCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sortCode.setText(" ");

        accNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accNo.setText(" ");

        balance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        balance.setText(" ");

        nameOfBank.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameOfBank.setText(" ");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Created On");

        createdOnDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createdOnDate.setText(" ");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Transactions");

        transactionsNbr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        transactionsNbr.setText(" ");

        javax.swing.GroupLayout accountInfoLayout = new javax.swing.GroupLayout(accountInfo);
        accountInfo.setLayout(accountInfoLayout);
        accountInfoLayout.setHorizontalGroup(
            accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInfoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24)
                    .addComponent(jLabel20))
                .addGap(34, 34, 34)
                .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(accNo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nameOfBank, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountInfoLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(28, 28, 28)
                        .addComponent(transactionsNbr, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(accountInfoLayout.createSequentialGroup()
                        .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(28, 28, 28)
                        .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastRDate, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(rate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createdOnDate, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        accountInfoLayout.setVerticalGroup(
            accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountInfoLayout.createSequentialGroup()
                        .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountInfoLayout.createSequentialGroup()
                                .addComponent(sortCode)
                                .addGap(26, 26, 26)
                                .addComponent(accNo)
                                .addGap(26, 26, 26)
                                .addComponent(balance))
                            .addGroup(accountInfoLayout.createSequentialGroup()
                                .addComponent(rate)
                                .addGap(24, 24, 24)
                                .addComponent(lastRDate)
                                .addGap(24, 24, 24)
                                .addComponent(createdOnDate))
                            .addGroup(accountInfoLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel22)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel23)))
                        .addGap(26, 26, 26)
                        .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameOfBank)
                            .addGroup(accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(transactionsNbr)
                                .addComponent(jLabel25))))
                    .addGroup(accountInfoLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel18)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel19)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel20)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        noAccountErrMsg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noAccountErrMsg.setForeground(new java.awt.Color(255, 51, 51));
        noAccountErrMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noAccountErrMsg.setText("NO ACCOUNT FOUND");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(accountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(noAccountErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(accountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noAccountErrMsg)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        displayAccInfo.addTab("display accounts info", jPanel2);

        withdrawBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        withdrawBtn.setText("Withdraw");

        depositBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        depositBtn.setText("Deposit");

        TXNAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXNAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Amount");

        javax.swing.GroupLayout depositWithdrawPanelLayout = new javax.swing.GroupLayout(depositWithdrawPanel);
        depositWithdrawPanel.setLayout(depositWithdrawPanelLayout);
        depositWithdrawPanelLayout.setHorizontalGroup(
            depositWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositWithdrawPanelLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addGroup(depositWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositWithdrawPanelLayout.createSequentialGroup()
                        .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(withdrawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositWithdrawPanelLayout.createSequentialGroup()
                        .addGroup(depositWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(TXNAmount))
                        .addGap(286, 286, 286))))
        );
        depositWithdrawPanelLayout.setVerticalGroup(
            depositWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositWithdrawPanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(TXNAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(depositWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawBtn)
                    .addComponent(depositBtn))
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(depositWithdrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(depositWithdrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        displayAccInfo.addTab("Deposit / withdraw", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayAccInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayAccInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField TXNAmount;
    protected javax.swing.JLabel accNo;
    protected javax.swing.JTextField accNoInput;
    protected javax.swing.JPanel accountInfo;
    protected javax.swing.JPanel accountInput;
    protected javax.swing.JLabel balance;
    protected javax.swing.JTextField balanceInput;
    protected javax.swing.JButton createBtn;
    protected javax.swing.JLabel createdOnDate;
    protected javax.swing.JButton depositBtn;
    protected javax.swing.JPanel depositWithdrawPanel;
    protected javax.swing.JTabbedPane displayAccInfo;
    protected javax.swing.JLabel infoMsg;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel11;
    protected javax.swing.JLabel jLabel12;
    protected javax.swing.JLabel jLabel13;
    protected javax.swing.JLabel jLabel14;
    protected javax.swing.JLabel jLabel15;
    protected javax.swing.JLabel jLabel16;
    protected javax.swing.JLabel jLabel17;
    protected javax.swing.JLabel jLabel18;
    protected javax.swing.JLabel jLabel19;
    protected javax.swing.JLabel jLabel20;
    protected javax.swing.JLabel jLabel21;
    protected javax.swing.JLabel jLabel22;
    protected javax.swing.JLabel jLabel23;
    protected javax.swing.JLabel jLabel24;
    protected javax.swing.JLabel jLabel25;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel jPanel3;
    protected javax.swing.JTextField jTextField1;
    protected javax.swing.JComboBox<String> jointInput;
    protected javax.swing.JLabel lastRDate;
    protected javax.swing.JTextField lastRDateInput;
    protected javax.swing.JLabel nameOfBank;
    protected javax.swing.JTextField nameOfBankInput;
    protected javax.swing.JLabel noAccountErrMsg;
    protected javax.swing.JLabel rate;
    protected javax.swing.JTextField rateInput;
    protected javax.swing.JLabel sortCode;
    protected javax.swing.JTextField sortcodeInput;
    protected javax.swing.JLabel transactionsNbr;
    protected javax.swing.JButton withdrawBtn;
    // End of variables declaration//GEN-END:variables
}
