/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package supermarket;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class ReorderCheckout extends javax.swing.JFrame {
    
    // Re-order quantity
    private int reorderQ;
    
    // bank.Customer
    bank.Customer customer;
    
    // product
    Product product;
    
    ConfirmBtnActionListener cbListener;
    
    /**
     * Set the ConfirmBtnActionListener
     */
    public void setConfirmBtnActionListener(ConfirmBtnActionListener cbListener) {
        this.cbListener = cbListener;
    }
        
    /**
     * Creates new form ReorderCheckout
     */
    public ReorderCheckout(int reorderQ, Product product) {
        initComponents();
        this.reorderQ = reorderQ;
        this.product = product;
        totalPriceValueLabel.setText(String.valueOf(this.reorderQ * this.product.getPrice()));
        totalProductsCountValueLabel.setText(String.valueOf(this.product.getNbItems() + reorderQ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reorderDetailsPanel = new javax.swing.JPanel();
        reorderDetailsNameLabel = new javax.swing.JLabel();
        totalPriceNameLabel = new javax.swing.JLabel();
        totalPriceValueLabel = new javax.swing.JLabel();
        totalProductsCountNameLabel = new javax.swing.JLabel();
        totalProductsCountValueLabel = new javax.swing.JLabel();
        bankAccountPanel = new javax.swing.JPanel();
        bankAccountDetailsLabel = new javax.swing.JLabel();
        emailAddressLabel = new javax.swing.JLabel();
        emailAddressText = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        accountTypeLabel = new javax.swing.JLabel();
        accountTypeCombox = new javax.swing.JComboBox();
        confirmBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reorderDetailsNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        reorderDetailsNameLabel.setText("Re-order Details");

        totalPriceNameLabel.setText("Total Price to pay");

        totalPriceValueLabel.setToolTipText("");
        totalPriceValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        totalProductsCountNameLabel.setText("Total Number of products");

        totalProductsCountValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout reorderDetailsPanelLayout = new javax.swing.GroupLayout(reorderDetailsPanel);
        reorderDetailsPanel.setLayout(reorderDetailsPanelLayout);
        reorderDetailsPanelLayout.setHorizontalGroup(
            reorderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reorderDetailsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(reorderDetailsNameLabel)
                .addGap(50, 50, 50))
            .addGroup(reorderDetailsPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(reorderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalProductsCountNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalPriceNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(reorderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalProductsCountValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPriceValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        reorderDetailsPanelLayout.setVerticalGroup(
            reorderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reorderDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reorderDetailsNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reorderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalPriceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPriceNameLabel))
                .addGap(18, 18, 18)
                .addGroup(reorderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalProductsCountNameLabel)
                    .addComponent(totalProductsCountValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bankAccountDetailsLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bankAccountDetailsLabel.setText("Bank Account Details");

        emailAddressLabel.setText("Email Address");

        passwordLabel.setText("Password");

        accountTypeLabel.setText("Account Type");

        accountTypeCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Current Account", "ISA Account", "Saving Account 1", "Saving Account 2" }));

        javax.swing.GroupLayout bankAccountPanelLayout = new javax.swing.GroupLayout(bankAccountPanel);
        bankAccountPanel.setLayout(bankAccountPanelLayout);
        bankAccountPanelLayout.setHorizontalGroup(
            bankAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankAccountPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bankAccountDetailsLabel)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(bankAccountPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(bankAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bankAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailAddressText, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(passwordText)
                    .addComponent(accountTypeCombox, 0, 1, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        bankAccountPanelLayout.setVerticalGroup(
            bankAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bankAccountDetailsLabel)
                .addGap(18, 18, 18)
                .addGroup(bankAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressLabel)
                    .addComponent(emailAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bankAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bankAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTypeLabel)
                    .addComponent(accountTypeCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmBtn.setText("Confirm to re-order");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleLabel.setText("You are ordering from the supermarket account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(titleLabel)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reorderDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reorderDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bankAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(confirmBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        
        // Confirm that the user bank account is valid
        if (!new bank.User().isUser(emailAddressText.getText().trim(), passwordText.getText().trim(), "Customer")) {
            JOptionPane.showMessageDialog(this, "Could not login.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
//            System.err.println("Valid user");
            bank.IAddress address = new bank.IAddress();
            customer = new bank.Customer(emailAddressText.getText().trim(), "-", "-", address, new Date());
            customer.readBankAccountsFromFile();
            
            String type = (String) accountTypeCombox.getSelectedItem();
            
            if ((type.equals("Current Account") && customer.OwnedAccounts[0] == null)
                    || (type.equals("ISA Account") && customer.OwnedAccounts[1] == null)
                    || (type.equals("Saving Account 1") && customer.OwnedAccounts[2] == null)
                    || (type.equals("Saving Account 2") && customer.OwnedAccounts[3] == null)) {
                JOptionPane.showMessageDialog(this, "You don't own a " + type + " account!", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                int i = accountTypeCombox.getSelectedIndex();
                bank.Account account = customer.OwnedAccounts[i];
                if (account.getBalance() < reorderQ * this.product.getPrice()) {
                    JOptionPane.showMessageDialog(this, "Insufficient funds!", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    account.withdraw(reorderQ * this.product.getPrice());
                    JOptionPane.showMessageDialog(this, "Transaction Succeeded!\n" + "Remaining balance: " + account.getBalance());
                    account.saveToFile(emailAddressText.getText(), i);
                    
                    // let the Employee know
                    this.cbListener.onClicked();
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    
    void changeTable(javax.swing.JTable tab, int col, String val, String ID) {
        for (int row = 0; row < tab.getRowCount(); row++) {
            System.err.println(tab.getValueAt(row, 0));
            if (((String) tab.getValueAt(row, 0)).equals(ID)) {
                tab.setValueAt(val, row, col);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReorderCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReorderCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReorderCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReorderCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReorderCheckout().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountTypeCombox;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JLabel bankAccountDetailsLabel;
    private javax.swing.JPanel bankAccountPanel;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JTextField emailAddressText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordText;
    private javax.swing.JLabel reorderDetailsNameLabel;
    private javax.swing.JPanel reorderDetailsPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalPriceNameLabel;
    private javax.swing.JLabel totalPriceValueLabel;
    private javax.swing.JLabel totalProductsCountNameLabel;
    private javax.swing.JLabel totalProductsCountValueLabel;
    // End of variables declaration//GEN-END:variables
}
